apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wi9hlfcui-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wi9hlfcui-python 
  name: wi9hlfcui-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wi9hlfcui-python 
